### ISSUE TITLE
Allowing extension

### ISSUE THREAD

**Issue by brettz9** [es-shims/Object.hasOwn#2]
Hi,

Thanks for the info on this being available.

And this is not a firm request as I understand if you have your own way to do things here but...

With linting, e.g., `eslint-plugin-node`'s [`file-extension-in-import`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/file-extension-in-import.md), one might enforce the requirement that an extension be present.

So, for the submodules, like `auto.js`, might you consider allowing the extension as well (in `package.json` `exports`)?

I'm partly asking also in case you're aware of any practices that have cropped up in the community around this.

I see that the [Node docs](https://nodejs.org/api/packages.html#packages_package_entry_points) give some examples which accommodate both (and speak to using wildcards when it becomes cumbersome).

Thanks!

**Comment by ljharb** [comment]
That requirement is simply invalid when importing from packages, precisely because the "exports" field allows package authors to remove the massive wart that is "a file extension".

The overwhelming practice in the community, for the last decade and unchanged now, is to omit file extensions whenever possible.

**Comment by brettz9** [comment]
Well, Deno seems to have reverted to it at least, and packages may have their own preferences, including to visibly distinguish from TypeScript or such imports. But understood.

**Comment by ljharb** [comment]
I'm not interested in following the lead of a project that's rejected the exact reasons why node is successful :-)
