### ISSUE TITLE
Typescript type declarations

### ISSUE THREAD

**Issue by djwashburn** [es-shims/Object.hasOwn#4]
It seems that the type declarations for this [do not exist](https://stackoverflow.com/questions/74440027/import-es-shim-object-hasown-polyfill-into-typescript), causing errors when attempting to use this package from TypeScript: 

> Could not find a declaration file for module 'object.hasown'. 'c:/Users/dwashburn/Projects/web-scheduler-frontend/node_modules/object.hasown/index.js' implicitly has an 'any' type.
>   Try `npm i --save-dev @types/object.hasown` if it exists or add a new declaration (.d.ts) file containing `declare module 'object.hasown';`ts(7016)

when attempting `npm i --save-dev @types/object.hasown` or ` yarn add --dev @types/object.hasown`:

> error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2fObject.hasown: Not found".

**Comment by ljharb** [comment]
That's often the case; the best way to make them exist is to make a PR to DT that adds them. I'm happy to be added as a maintainer of them, and review them, though.

Closing since there's nothing actionable in this repo.
